PLAYER_WIDTH:int = 20
PLAYER_HEIGHT:int = 50
PLAYER_STEP:int = 4 # how many pixels a player can climb
PLAYER_SPEED:float = 2
PLAYER_JUMP:float = 3
PLAYER_CRIT_CHANCE = 0.25

# PLAYER OFFSETS IN Y AXIS
PLYOFF_HEAD = 0
PLYOFF_BODY = 17
PLYOFF_LEGS = 34

FPS = 60
WINDOW_WIDTH:int = 1920
WINDOW_HEIGHT:int = 1080

# WEAPON SELECTOR
WEP_SELECTOR_SIZE:int = 40
WEP_SELECTOR_GAP:int = 10
WEP_SELECTOR_COLS:int = 4

# WEAPON
WEAPON_ANGLE_STEP = 2