PLAYER_WIDTH:int = 20
PLAYER_HEIGHT:int = 50
PLAYER_STEP:int = 4 # how many pixels a player can climb
PLAYER_SPEED:float = 2
PLAYER_JUMP:float = 3

WINDOW_WIDTH:int = 1280
WINDOW_HEIGHT:int = 720

# WEAPON SELECTOR
WEP_SELECTOR_SIZE:int = 40
WEP_SELECTOR_GAP:int = 10
WEP_SELECTOR_COLS:int = 4